package main

// knownTickers is a set of valid US stock tickers (NYSE + NASDAQ).
// Covers S&P 500, NASDAQ 100, popular growth/meme stocks, and common ETFs.
var knownTickers = map[string]bool{
	// S&P 500 / Large caps
	"A": true, "AAL": true, "AAP": true, "AAPL": true, "ABBV": true,
	"ABC": true, "ABMD": true, "ABT": true, "ACN": true, "ADBE": true,
	"ADI": true, "ADM": true, "ADP": true, "ADSK": true, "AEE": true,
	"AEP": true, "AES": true, "AFL": true, "AIG": true, "AIZ": true,
	"AJG": true, "AKAM": true, "ALB": true, "ALGN": true, "ALK": true,
	"ALL": true, "ALLE": true, "AMAT": true, "AMCR": true, "AMD": true,
	"AME": true, "AMGN": true, "AMP": true, "AMT": true, "AMZN": true,
	"ANET": true, "ANSS": true, "AON": true, "AOS": true, "APA": true,
	"APD": true, "APH": true, "APTV": true, "ARE": true, "ATO": true,
	"AVB": true, "AVGO": true, "AVY": true, "AWK": true, "AXP": true,
	"AZO": true, "BA": true, "BAC": true, "BALL": true, "BAX": true,
	"BBWI": true, "BBY": true, "BDX": true, "BEN": true, "BG": true,
	"BIIB": true, "BIO": true, "BK": true, "BKNG": true, "BKR": true,
	"BLK": true, "BMY": true, "BR": true, "BRK": true, "BSX": true,
	"BWA": true, "BXP": true, "C": true, "CAG": true, "CAH": true,
	"CARR": true, "CAT": true, "CB": true, "CBOE": true, "CBRE": true,
	"CCI": true, "CCL": true, "CDNS": true, "CDW": true, "CE": true,
	"CF": true, "CFG": true, "CHD": true, "CHRW": true, "CHTR": true,
	"CI": true, "CINF": true, "CL": true, "CLX": true, "CMA": true,
	"CMCSA": true, "CME": true, "CMG": true, "CMI": true, "CMS": true,
	"CNC": true, "CNP": true, "COF": true, "COO": true, "COP": true,
	"COST": true, "CPB": true, "CPRT": true, "CRL": true, "CRM": true,
	"CSCO": true, "CSX": true, "CTAS": true, "CTLT": true, "CTRA": true,
	"CTSH": true, "CTVA": true, "CVS": true, "CVX": true, "D": true,
	"DAL": true, "DD": true, "DE": true, "DFS": true, "DG": true,
	"DGX": true, "DHI": true, "DHR": true, "DIS": true, "DISH": true,
	"DLR": true, "DLTR": true, "DOV": true, "DOW": true, "DPZ": true,
	"DRE": true, "DRI": true, "DTE": true, "DUK": true, "DVA": true,
	"DVN": true, "DXC": true, "DXCM": true, "EA": true, "EBAY": true,
	"ECL": true, "ED": true, "EFX": true, "EG": true, "EIX": true,
	"EL": true, "ELV": true, "EMN": true, "EMR": true, "ENPH": true,
	"EOG": true, "EPAM": true, "EQIX": true, "EQR": true, "EQT": true,
	"ES": true, "ESS": true, "ETN": true, "ETR": true, "ETSY": true,
	"EVRG": true, "EW": true, "EXC": true, "EXPD": true, "EXPE": true,
	"EXR": true, "F": true, "FANG": true, "FAST": true, "FCX": true,
	"FDS": true, "FDX": true, "FE": true, "FFIV": true, "FI": true,
	"FICO": true, "FIS": true, "FITB": true, "FLT": true, "FMC": true,
	"FOX": true, "FOXA": true, "FRC": true, "FRT": true, "FTNT": true,
	"FTV": true, "GD": true, "GE": true, "GILD": true, "GIS": true,
	"GL": true, "GLW": true, "GM": true, "GNRC": true, "GOOGL": true,
	"GOOG": true, "GPC": true, "GPN": true, "GPS": true, "GRMN": true,
	"GS": true, "GWW": true, "HAL": true, "HAS": true, "HBAN": true,
	"HCA": true, "HD": true, "HES": true, "HIG": true, "HII": true,
	"HLT": true, "HOLX": true, "HON": true, "HPE": true, "HPQ": true,
	"HRL": true, "HSIC": true, "HST": true, "HSY": true, "HUM": true,
	"HWM": true, "IBM": true, "ICE": true, "IDXX": true, "IEX": true,
	"IFF": true, "ILMN": true, "INCY": true, "INTC": true, "INTU": true,
	"INVH": true, "IP": true, "IPG": true, "IQV": true, "IR": true,
	"IRM": true, "ISRG": true, "IT": true, "ITW": true, "IVZ": true,
	"J": true, "JBHT": true, "JCI": true, "JKHY": true, "JNJ": true,
	"JNPR": true, "JPM": true, "K": true, "KEY": true, "KEYS": true,
	"KHC": true, "KIM": true, "KLAC": true, "KMB": true, "KMI": true,
	"KMX": true, "KO": true, "KR": true, "L": true, "LDOS": true,
	"LEN": true, "LH": true, "LHX": true, "LIN": true, "LKQ": true,
	"LLY": true, "LMT": true, "LNC": true, "LNT": true, "LOW": true,
	"LRCX": true, "LUMN": true, "LUV": true, "LVS": true, "LW": true,
	"LYB": true, "LYV": true, "MA": true, "MAA": true, "MAR": true,
	"MAS": true, "MCD": true, "MCHP": true, "MCK": true, "MCO": true,
	"MDLZ": true, "MDT": true, "MET": true, "META": true, "MGM": true,
	"MHK": true, "MKC": true, "MKTX": true, "MLM": true, "MMC": true,
	"MMM": true, "MNST": true, "MO": true, "MOH": true, "MOS": true,
	"MPC": true, "MPWR": true, "MRK": true, "MRO": true, "MS": true,
	"MSCI": true, "MSFT": true, "MSI": true, "MTB": true, "MTD": true,
	"MU": true, "NCLH": true, "NDAQ": true, "NDSN": true, "NEE": true,
	"NEM": true, "NFLX": true, "NI": true, "NKE": true, "NOC": true,
	"NOW": true, "NRG": true, "NSC": true, "NTAP": true, "NTRS": true,
	"NUE": true, "NVDA": true, "NVR": true, "NWL": true, "NWS": true,
	"NWSA": true, "NXPI": true, "O": true, "ODW": true, "OKE": true,
	"OMC": true, "ON": true, "ORCL": true, "ORLY": true, "OTIS": true,
	"OXY": true, "PARA": true, "PAYC": true, "PAYX": true, "PCAR": true,
	"PCG": true, "PEAK": true, "PEG": true, "PEP": true, "PFE": true,
	"PFG": true, "PG": true, "PGR": true, "PH": true, "PHM": true,
	"PKG": true, "PKI": true, "PLD": true, "PM": true, "PNC": true,
	"PNR": true, "PNW": true, "POOL": true, "PPG": true, "PPL": true,
	"PRU": true, "PSA": true, "PSX": true, "PTC": true, "PWR": true,
	"PXD": true, "PYPL": true, "QCOM": true, "QRVO": true, "RCL": true,
	"RE": true, "REG": true, "REGN": true, "RF": true, "RHI": true,
	"RJF": true, "RL": true, "RMD": true, "ROK": true, "ROL": true,
	"ROP": true, "ROST": true, "RSG": true, "RTX": true, "SBAC": true,
	"SBUX": true, "SEDG": true, "SEE": true, "SHW": true, "SJM": true,
	"SLB": true, "SNA": true, "SNPS": true, "SO": true, "SPG": true,
	"SPGI": true, "SRE": true, "STE": true, "STT": true, "STX": true,
	"STZ": true, "SWK": true, "SWKS": true, "SYF": true, "SYK": true,
	"SYY": true, "T": true, "TAP": true, "TDG": true, "TDY": true,
	"TECH": true, "TEL": true, "TER": true, "TFC": true, "TFX": true,
	"TGT": true, "TJX": true, "TMO": true, "TMUS": true, "TPR": true,
	"TRMB": true, "TROW": true, "TRV": true, "TSCO": true, "TSLA": true,
	"TSN": true, "TT": true, "TTWO": true, "TXN": true, "TXT": true,
	"TYL": true, "UAL": true, "UDR": true, "UHS": true, "ULTA": true,
	"UNH": true, "UNP": true, "UPS": true, "URI": true, "USB": true,
	"V": true, "VFC": true, "VICI": true, "VLO": true, "VMC": true,
	"VNO": true, "VRSK": true, "VRSN": true, "VRTX": true, "VTR": true,
	"VTRS": true, "VZ": true, "WAB": true, "WAT": true, "WBA": true,
	"WBD": true, "WDC": true, "WEC": true, "WELL": true, "WFC": true,
	"WHR": true, "WM": true, "WMB": true, "WMT": true, "WRB": true,
	"WRK": true, "WST": true, "WTW": true, "WY": true, "WYNN": true,
	"XEL": true, "XOM": true, "XRAY": true, "XYL": true, "YUM": true,
	"ZBH": true, "ZBRA": true, "ZION": true, "ZTS": true,

	// NASDAQ 100 extras (not already in S&P 500 above)
	"ARM": true, "ASML": true, "CEG": true, "CRWD": true, "CSGP": true,
	"DDOG": true, "GFS": true, "KDP": true, "LULU": true, "MRVL": true,
	"MRNA": true, "ODFL": true, "PANW": true, "PDD": true, "SIRI": true,
	"TEAM": true, "TTD": true, "WDAY": true, "ZS": true,

	// Popular meme / WSB stocks
	"GME": true, "AMC": true, "BB": true, "NOK": true, "BBBY": true,
	"KOSS": true, "EXPR": true, "CLOV": true, "WISH": true, "WKHS": true,
	"RIDE": true, "GOEV": true, "SPCE": true, "NNDM": true, "MVIS": true,
	"SNDL": true, "TLRY": true, "CGC": true, "ACB": true, "APHA": true,
	"FIZZ": true, "OCGN": true, "ATOS": true, "NAKD": true, "TRCH": true,
	"CTRM": true, "GNUS": true, "IDEX": true, "ZOM": true, "SENS": true,
	"NKLA": true, "HYLN": true, "XPEV": true, "NIO": true, "LI": true,
	"RIVN": true, "LCID": true, "FSR": true, "SOLO": true, "KNDI": true,
	"PLTR": true, "OPEN": true, "HOOD": true, "SOFI": true,
	"AFRM": true, "UPST": true, "LMND": true, "ROOT": true, "METV": true,
	"SPRT": true, "IRNT": true, "PHUN": true, "SDC": true, "SKLZ": true,
	"RBLX": true, "COIN": true, "MSTR": true, "RIOT": true, "MARA": true,
	"HUT": true, "BTBT": true, "CAN": true, "EBON": true, "BITF": true,
	"ARBK": true, "IREN": true, "CIFR": true, "CLSK": true, "GREE": true,
	"BTCM": true, "SOS": true,

	// Popular growth / tech
	"SNOW": true, "PATH": true, "NET": true,
	"OKTA": true, "TWLO": true, "MDB": true, "ESTC": true, "FSLY": true,
	"SUMO": true, "APPN": true, "HUBS": true, "BILL": true, "CFLT": true,
	"GTLB": true, "SMAR": true, "BOX": true, "DOCU": true, "DBX": true,
	"WORK": true, "ZM": true, "PTON": true, "NKTR": true, "ROKU": true,
	"SPOT": true, "SHOP": true, "SQ": true, "TWTR": true, "SNAP": true,
	"PINS": true, "UBER": true, "LYFT": true, "DASH": true,
	"TRIP": true, "YELP": true, "GRUB": true,
	"AMRN": true, "SGEN": true, "ALNY": true, "BMRN": true, "SRPT": true,
	"BLUE": true, "FATE": true, "NTLA": true, "CRSP": true,
	"BEAM": true, "PACB": true, "NVAX": true, "BNTX": true,

	// Popular ETFs sometimes referenced
	"SPY": true, "QQQ": true, "IWM": true, "DIA": true, "VTI": true,
	"VOO": true, "GLD": true, "SLV": true, "TLT": true, "HYG": true,
	"XLF": true, "XLE": true, "XLK": true, "XLV": true, "XLI": true,
	"ARKK": true, "ARKG": true, "ARKW": true, "ARKF": true, "ARKQ": true,
	"SOXS": true, "SOXL": true, "TQQQ": true, "SQQQ": true, "SPXU": true,
	"UVXY": true, "VXX": true, "SVXY": true,
}
